[build]
publish = "."

[[redirects]]
from = "/"
to = "/public/index.html"
status = 200

[[redirects]]
from = "/assets/*"
to = "/public/assets/:splat"
status = 200

[[redirects]]
from = "/templates/*"
to = "/templates/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/public/:splat"
status = 200
